specVersion: 0.2.0
name: astarsts-portfolio-usdt-data
version: 0.0.1
description: This SubQuery project can be use as a starting point for Astar network
repository: https://github.com/subquery/astar-subql-starters
schema:
  file: ./schema.graphql
network:
  endpoint: wss://astar.api.onfinality.io/public-wss
  genesisHash: '0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6'
  dictionary: https://api.subquery.network/sq/subquery/astar-dictionary
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Moonbeam
    startBlock: 220690
    assets:
      usdt:
        file: './usdt.abi.json'
    processor:
      file: './node_modules/@subql/contract-processors/dist/moonbeam.js'
      options:
        abi: usdt
        address: '0x3795C36e7D12A8c252A20C5a7B455f7c57b60283'
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleERC20Transfer
          kind: substrate/MoonbeamEvent
          filter:
            topics:
              - Transfer(address indexed from,address indexed to,uint256 value)
